name: Backend

on:
  push:
    branches: [master]

jobs:
  backend:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Run server
        working-directory: ./backend
        run: |
          npm install
          cp -a /home/byteman/collettabooking-config/backend/. ./
          npm run build
