name: Deploy CollettaBooking

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  BE_DIRECTORY: ./backend
  BE_DIST_DIRECTORY: /srv/colletta-booking/backend/
  FE_DIRECTORY: ./frontend

on:
  push:
    branches: [master]

jobs:
  backend:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install and build server
        working-directory: ${{ env.BE_DIRECTORY }}
        run: |
          npm install
          cp -a /home/byteman/collettabooking-config/backend/. ./
          npm run build
          cp -R ./ ${{ env.BE_DIST_DIRECTORY }}
      - name: Run server
        working-directory: ${{ env.BE_DIST_DIRECTORY }}
        run: |
          rm -R ./src
          pm2 restart cb-backend
  frontend:
    runs-on: self-hosted
    needs: backend

    steps:
      - name: Install Vercel CLI
        run: npm install --global vercel
      - name: Deploy to Vercel
        working-directory: ${{ env.FE_DIRECTORY }}
        run: |
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_ACCESS_TOKEN }}
          vercel build --prod --token=${{ secrets.VERCEL_ACCESS_TOKEN }}
          vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
