name: Backend

on:
  push:
    branches: [master]

jobs:
  backend:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install and build server
        working-directory: ./backend
        run: |
          npm install
          cp -a /home/byteman/collettabooking-config/backend/. ./
          npm run build
          cp -R ./ /srv/colletta-booking/backend/
      - name: Run server
        working-directory: /srv/colletta-booking/backend/
        run: |
          rm -R ./src
          pm2 restart cb-backend
